/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier.management.system;

import courier.management.system.models.Parcel;
import java.util.List;

public class BranchDashboard extends javax.swing.JPanel {

    int branchId;
    /**
     * Creates new form BranchDashboard
     */
    public BranchDashboard(int branchId) {
        initComponents();
        this.branchId = branchId;
        setAllParcels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createParcelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        parcelsPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createParcelButton.setText("Create Parcel");
        createParcelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createParcelButtonMouseClicked(evt);
            }
        });
        createParcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createParcelButtonActionPerformed(evt);
            }
        });
        add(createParcelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, -1));

        jLabel1.setText("Available parcels:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        parcelsPanel.setLayout(new javax.swing.BoxLayout(parcelsPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(parcelsPanel);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 480, 230));

        refreshButton.setText("Refresh order");
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createParcelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createParcelButtonMouseClicked
        // TODO add your handling code here:
        
        new CreateParcel(branchId).setVisible(true);
    }//GEN-LAST:event_createParcelButtonMouseClicked

    private void createParcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createParcelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createParcelButtonActionPerformed

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        // TODO add your handling code here:
        setAllParcels();
    }//GEN-LAST:event_refreshButtonMouseClicked

    
    private void setAllParcels(){
        List<Parcel> parcels = DB.getInstance().getAllParcelByBranch(branchId);
        parcelsPanel.removeAll();
        
        
        for(Parcel parcel: parcels){
            parcelsPanel.add(new ParcelItemView(parcel, branchId));
        }
        
        parcelsPanel.revalidate();
        parcelsPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createParcelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel parcelsPanel;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
