/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier.management.system;

import courier.management.system.models.Branch;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class CreateManager extends javax.swing.JFrame {
    
    List<Branch> branchList;
    /**
     * Creates new form CreateManager
     */
    public CreateManager() {
        initComponents();
        setBranches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createManagerButton = new javax.swing.JButton();
        branchListComboBox = new javax.swing.JComboBox<>();
        managerUserNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        managerPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Create manager");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 220, 30));

        jLabel2.setText("Branch:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, -1));

        jLabel3.setText("username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, -1));

        createManagerButton.setText("Create");
        createManagerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createManagerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(createManagerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        getContentPane().add(branchListComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, -1));
        getContentPane().add(managerUserNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        jLabel4.setText("password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, -1));
        getContentPane().add(managerPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createManagerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createManagerButtonMouseClicked
        // TODO add your handling code here:
        createManager();
        
    }//GEN-LAST:event_createManagerButtonMouseClicked

    
    private void setBranches(){
        branchList = DB.getInstance().getAllBranches();
        
        for(Branch branch: branchList){
            branchListComboBox.addItem(branch.getName());
        }
        
    }
    
    private void createManager(){
        int branchId = branchList.get(branchListComboBox.getSelectedIndex()).getId();
        String managerUserName = managerUserNameField.getText();
        String managerPassword = String.copyValueOf(managerPasswordField.getPassword());
        
        if(managerUserName.isEmpty() || managerPassword.isEmpty()){
            JOptionPane.showMessageDialog(null, "Field empty.");
        } else {
            DB.getInstance().createManager(managerUserName, managerPassword, branchId);
            
            JOptionPane.showMessageDialog(null, "Manager Created.");
            
            dispose();
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> branchListComboBox;
    private javax.swing.JButton createManagerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField managerPasswordField;
    private javax.swing.JTextField managerUserNameField;
    // End of variables declaration//GEN-END:variables

}
