/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier.management.system;

import courier.management.system.models.Parcel;
import javax.swing.JOptionPane;

public class ParcelItemView extends javax.swing.JPanel {

    int currentBranchId;
    Parcel parcel;
    
    /**
     * Creates new form ParcelItemView
     */
    public ParcelItemView(Parcel parcel, int currentBranchId) {
        initComponents();
        this.parcel = parcel;
        this.currentBranchId = currentBranchId;
        
        setParcelDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JLabel();
        typeField = new javax.swing.JLabel();
        descriptionField = new javax.swing.JLabel();
        deliverButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Description:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Type:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, -1));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 20));
        add(typeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 270, 20));
        add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 230, 20));

        deliverButton.setText("Deliver");
        deliverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliverButtonMouseClicked(evt);
            }
        });
        add(deliverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 70, -1));

        transferButton.setText("Transfer");
        transferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferButtonMouseClicked(evt);
            }
        });
        add(transferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void transferButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferButtonMouseClicked
        // TODO add your handling code here:
        new Transfer(parcel, currentBranchId).setVisible(true);
    }//GEN-LAST:event_transferButtonMouseClicked

    private void deliverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliverButtonMouseClicked
        // TODO add your handling code here:
        DB.getInstance().deliverParcel(parcel.getId());
        
        JOptionPane.showMessageDialog(null, "Delivered successfully.");
    }//GEN-LAST:event_deliverButtonMouseClicked


    private void setParcelDetails(){
        nameField.setText(parcel.getName());
        typeField.setText(parcel.getType());
        descriptionField.setText(parcel.getDescription());
    }
    
    public void hideButtons(){
        deliverButton.setVisible(false);
        transferButton.setVisible(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliverButton;
    private javax.swing.JLabel descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameField;
    private javax.swing.JButton transferButton;
    private javax.swing.JLabel typeField;
    // End of variables declaration//GEN-END:variables
}
