/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier.management.system;

import courier.management.system.models.Branch;
import courier.management.system.models.Parcel;
import java.util.List;
import javax.swing.JOptionPane;


public class Transfer extends javax.swing.JFrame {

    int currentBranchId;
    Parcel parcel;
    List<Branch> branchList;
    /**
     * Creates new form AddParcel
     */
    public Transfer(Parcel parcel, int currentBranchId) {
        initComponents();
        this.parcel = parcel;
        this.currentBranchId = currentBranchId;
        setBranches();
        
        ParcelItemView parcelItemView = new ParcelItemView(parcel, currentBranchId);
        parcelItemView.hideButtons();
        parcelViewPanel.add(parcelItemView);
    }
    
    private void setBranches(){
        branchList = DB.getInstance().getAllBranches();
        
        for(Branch branch: branchList){
            branchListComboBox.addItem(branch.getName());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        branchListComboBox = new javax.swing.JComboBox<>();
        transferButton = new javax.swing.JButton();
        parcelViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionField = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Transaction");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 220, 30));

        jLabel3.setText("Description:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, -1));

        getContentPane().add(branchListComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 170, -1));

        transferButton.setText("Transfer");
        transferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferButtonMouseClicked(evt);
            }
        });
        getContentPane().add(transferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));
        getContentPane().add(parcelViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 370, 100));

        descriptionField.setColumns(20);
        descriptionField.setRows(5);
        jScrollPane1.setViewportView(descriptionField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, -1));

        jLabel4.setText("To Branch:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transferButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferButtonMouseClicked
        // TODO add your handling code here:
        
        int parchelId = parcel.getId();
        int fromBranch = currentBranchId;
        int toBranch = branchList.get(branchListComboBox.getSelectedIndex()).getId();
        String description = descriptionField.getText();
        
        DB.getInstance().makeTransaction(
                parchelId,
                "transfer",
                fromBranch,
                toBranch,
                description
        );
        
        JOptionPane.showMessageDialog(null, "Transfer successful");
        dispose();
        
        
        
    }//GEN-LAST:event_transferButtonMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> branchListComboBox;
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel parcelViewPanel;
    private javax.swing.JButton transferButton;
    // End of variables declaration//GEN-END:variables
}
